# Generated by Django 4.2.1 on 2023-05-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superheroe',
            name='motivo',
            field=models.TextField(),
        ),
    ]
