# Generated by Django 4.2.1 on 2023-06-05 16:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_superheroe_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superheroe',
            name='motivo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
